<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SlkAcl\Module'                      => __DIR__ . '/Module.php',
    'SlkAcl\Entity\User'                 => __DIR__ . '/src/SlkAcl/Entity/User.php',
    'SlkAcl\Service\Acl'                 => __DIR__ . '/src/SlkAcl/Service/Acl.php',
    'SlkAcl\Service\Log'                 => __DIR__ . '/src/SlkAcl/Service/Log.php',
    'SlkAcl\Controller\AccessController' => __DIR__ . '/src/SlkAcl/Controller/AccessController.php',
);